# This is a simplified config where the rest of the settings are omitted and will be set by default.
# See https://gate.minekube.com/guide/config/ for the full configuration options.
config:
  bind: 0.0.0.0:25577
  onlineMode: true
  builtinCommands: false
  servers:
  try:
  # Disabling it allows our global-chat plugin to cancel messages.
  forceKeyAuthentication: false

  status:
    # The message of the day in legacy '§' format or modern text component '{"text":"...", ...}' json.
    motd: |
      §6A Gate Proxy
      §bVisit ➞ §fgithub.com/minekube/gate
    # The maximum players shown (is not the actual player limit!).
    showMaxPlayers: 1000
    # The server image (optimal 64x64); a path of an image file or the base64 data uri.
    favicon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAABoVJREFUeJztWluIVVUY/tbe+1xmHJ2DTepRximd8SFyJIrsRlJCiBBdJCoUgygMeip8KIQeCqEH6SEqEiQCNQkxJKKMiCyIoDSyiS5OXsZRx/HGeOZyzp5z9l49rNt/Zu+zzz4zYw/u872s//zrchb//61/rfWvzTBN8NNvhuuL10RZGjW6cgkAYC/o5nHG9scuMyUzJy3K7LzIPuyWN+IMHYA1rV43EFiYMsy73JWedYVnue/rOju3NODZycFDpq/VLsqJCQCAdeW8rivPN3JmzgOinszKWnx/zcn7hQumpS2YYs2ZX7N9GEsSz4DEG0BTiNKee66otDMBapeHvgYA2GwuGaUtMHDl1LHZmyUA59ZVQvDLRjl5SYtW17qo7oGlrpZD4hngEFl7m9kZAIBbOKErU9wTdW4BAFC5cDFy4Bc+NMEo19Y644nu2FSHUUO7ARCmALAW9ioxbPtlQJMBVQzQKFztAwC0Fv7WOn9KG+rhMOy+ZWWsCRz8/JNY7bZidUA3MjYR0O16iTBFxqFU9+0AANZxR6B94hmgo6N7uFWvEwvLAQBrtwQt3JXvABDDw3lydLWlnR1JuAU5XXXirfe1PFQeqzncZd+N/j+Jj5Z1B3T7txYBAOn8Ga1ja9xmDACaBjBBMM08razIxfDDvQ/V7rlwjpFphMykRJlNGV2L2FaRCo25Gjk7CwAoczOXcXnw6bDEGPWWwvMn/w3o0nkvpKVAkwGxW+alF5n0rEO6Zoi3U1JuzRqdJezMN3QGx93wduTf/r7yVQDAqD8JwDABiB8Yo9BkQOyWyvMt4t6NdIjXAfCNPaL5gUGjU54vmqO1RsvyyL/t7XsHgGHCOLkMzWPmfwu8jOkg8QxIvAGil0DeBBwd6BT102lTR5aAQlXAm0J9dsDsmyd2vBZror0/vwwAOHb3e1pn+eaan2bCl40GxiYDYrfMTNn+bNvUWcaObE8/AKDY+53WZXvWijrl+ToHojD037NTTIOZvhb530IMz08OLaUjijEanskNBmPOdJdR5p8SQo5Y1fdLVT0Zy+J/hC3XuEWSOzTNk0/JvCTZDePEgyYDjFgJ1o6MGLm9/biUlsiSbAPEkC0RxFBr32k8BigwZiI/54YDKpfQ3AUaROINYLg4ec5oLx8EAPAtj2sV2zt+FgBgWWIJ+L65ZNP9yKt9954N+IT2kyRvEEb9x34Vhyx+RiVeg3NrMkBLXdtMdLn0WfAhwfOGAQBMXsEcx7SxLJoTqm3UGQQ/BZ9sfmUit8lpjYXcChk/Jcq5KwNPZE0GxG5Zqagbjyg9z3ideta2lVu0tUv93wIA+Hp5JP6S7qCNgcYAn5sp8NDXr2qk2voCusQzIPEGCF8ClUJQVy5vEj2ckwAA31+i6wgtiysOhX52M1Ms++lFAEDf6g/MlMgSqHB/EAA6rExI5rU2mgwI1apDkTwQAeZQxHaPigMR58bSjAUM2XLUfNxUvPNHACYYFntMu6z0bD2ofAD1ukcCnwu/EwDWHXnFdBrYXnfcJgO0RK2lDkVDHwf3lomJBwEAnTTnV9Qi9fxUnWIChWJFLZzfLEKO8rxLjr8j8rEEqH4wCUHNuJR4BkR/KDmw3TBABddFm0XHncOmQ8689+tDEckaM3lB4qXqpBIAHN61X8vpa1cD9e2WGGdUPohc8ILfLADm4lNj3TMAYGuCF6bEMyDxBgjfBhWN6A1RLYfhPQAAvmWTrqpaDu3iu2CaNudyWaSyIl02r2iWgk0OUa2OqLdIqiGK+pr2dM7VqHsoSzwDIi3EvydbS9c2UZ59lwOAb92kq6zFG82An8pAY1n6edhJp0UElU9oNP1KP5Iq+aJmlLwAT/X8dLweFvz03GvWJASR+QBqOX5alBe9RxkAtLtf6MXrndpn2j39rOi7c9iclBYtUmyIvKhMcMGAcV4eJOpOoO42BzToeYXEMyDxBmj47v7XvkcAAF6lfJfSdS/+4xcl22nxhajT+Zz5k4gUGA2Cfe6VQH2cE16VIgbtKRLPgIbz1F5FbFG2kzqidIMjq7Unuju+4QBQGtir+/D1ZpsEqhlBvV61xSkEPR/K2kY9r5B4BsxK/u63XffRnysAYFXP0X+Uws/eBgCwFj4Rb8DrtN7DkHgGzPytKojjAHDOfVJ7bAnkU9vAn9MZr8rzs+F1isQzIPEGuC6PGFPx1es3K5EDwMOrcrUbC+h5ZZ7pvz6Tkkg8A/4DJe7648CQ3eMAAAAASUVORK5CYII=
    # Whether to log ping requests in the console.
    logPingRequests: false
    # Whether the proxy should present itself as Forge/FML-compatible server.
    announceForge: false

  requireBuiltinCommandPermissions: true

  forwarding:
    mode: velocity
    velocitySecret: '6YHBaxYVAWVC'
